name: carp_webservices_example
description: An small example of how to usee the CARP web service package.
version: 1.1.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/carp_core
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carp_core: ^1.1.0
  carp_mobile_sensing: ^1.1.0
  # carp_core:
  #   path: ../../../carp_core
  # carp_mobile_sensing:
  #   path: ../../../carp_mobile_sensing
  carp_webservices:
    path: ../

dev_dependencies:

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
