name: carp_health_package_example
description: Examples of how to use the CANS Health Package.
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  carp_health_package:
    path: ../

flutter:
  uses-material-design: true
