name: carp_mobile_sensing_app
description: The CARP Mobile Sensing App
version: 1.11.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/apps/carp_mobile_sensing_app
publish_to: 'none' 

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0
  permission_handler: ^11.0.0  
  
  #carp_serializable: ^1.1.0
  #carp_core: ^0.30.0
  #carp_mobile_sensing: ^0.30.6
  #carp_connectivity_package: ^0.30.0
  #carp_context_package: ^0.30.1
  #carp_audio_package: ^0.30.0
  #carp_communication_package: ^0.30.0
  #carp_apps_package: ^0.30.0
  #carp_backend: ^0.30.0
  #carp_webservices: ^0.30.0
  #carp_health_package: ^2.0.0
  #carp_firebase_backend: ^0.30.0

  # carp_esense_package: ^0.30.2
  # carp_movisens_package: ^0.32.0

  research_package: ^2.0.0
  # health: ^8.1.0

# Overriding carp libraries to use the local copy
dependency_overrides:
  carp_serializable:
    path: ../../carp_serializable/
  carp_core:
    path: ../../carp_core/
  carp_mobile_sensing:
    path: ../../carp_mobile_sensing/
  carp_context_package:
    path: ../../packages/carp_context_package/
  carp_connectivity_package:
    path: ../../packages/carp_connectivity_package/
  carp_communication_package:
    path: ../../packages/carp_communication_package/
  carp_audio_package:
    path: ../../packages/carp_audio_package/
  carp_apps_package:
    path: ../../packages/carp_apps_package/
  carp_esense_package:
    path: ../../packages/carp_esense_package/
  carp_polar_package:
    path: ../../packages/carp_polar_package/
  carp_movisens_package:
    path: ../../packages/carp_movisens_package/
  carp_health_package:
    path: ../../packages/carp_health_package/
  carp_backend:
    path: ../../backends/carp_backend/
  carp_webservices:
    path: ../../backends/carp_webservices/
  carp_movesense_package:
    path: ../../packages/carp_movesense_package/
  carp_cortrium_package:
    path: ../../../carp_cortrium_package/

  # research_package:
  #   path: ../../../../research.package/

  # esense_flutter:
  #   path: ../../../../flutter-plugins/packages/esense_flutter/
  
  # location:
  #   git:
  #     url: https://github.com/fairuzmn/flutterlocation.git
  #     ref: location-v5.5.0.0-dev.9-fix
  #     path: packages/location
  
  # due to this issue https://github.com/builttoroam/device_calendar/issues/586 
  device_calendar:
    git: https://github.com/bardram/device_calendar

  # due to this issue https://github.com/petri-lipponen-movesense/mdsflutter/issues/36 
  mdsflutter:
    git:
      url: https://github.com/Panosfunk/mdsflutter.git
      ref: master

  # due to this issue https://github.com/cph-cachet/carp_studies_app/issues/427
  polar: 7.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter  
  test: any 
  flutter_lints: any
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# Is used to change the default app launch icons on iOS and Android.
# To install:
#  1. import the 'flutter_launcher_icons' package above
#  2. add the 'flutter_icons:' section below
#  3. run 'flutter pub get'
#  3. run 'flutter pub pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: "assets/cachet_logo.png"


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/study.png
    - assets/cachet_logo.png
    - assets/logo.png

