name: carp_polar_package_example
description: Example project for the CAMS Polar Sampling Package.
homepage: https://github.com/cph-cachet/carp.sensing-flutter
publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  carp_polar_package:
    path: ../

dev_dependencies:
#  flutter_test:
#    sdk: flutter
