name: carp_webservices
description: Flutter API for accessing the CARP web services - authentication, file management, data points, and app-specific collections of documents.
version: 3.1.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/backends/carp_webservices

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.2.0
  carp_core: ^1.6.0
  carp_mobile_sensing: ^1.6.0

  http: ^1.1.0
  http_parser: ^4.0.0
  json_annotation: ^4.8.0
  retry: ^3.1.0
  meta: ^1.7.0
  form_field_validator: ^1.1.0
  url_launcher: ^6.0.9
  jwt_decoder: ^2.0.1
  oidc: ^0.5.2
  oidc_default_store: ^0.2.0+8

  firebase_messaging: ^14.9.3

# Overriding carp libraries to use the local copy
# Remove this before release of package
dependency_overrides:
#   carp_serializable:
#     path: ../../carp_serializable/
#   carp_core:
#     path: ../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../carp_mobile_sensing/

dev_dependencies:
  build_runner: any
  json_serializable: any
  test: any
  flutter_lints: any
  mockito: any
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.2.3
  iso_duration_parser: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - asset/images/
