name: carp_esense_package_example
description: Example project for the CAMS eSense Package.
publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  carp_esense_package:
    path: ../

dev_dependencies:

flutter:
  uses-material-design: true
