name: carp_survey_package_example
description: Examples of how to use the carp_survey_package.
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  carp_survey_package:
    path: ../
