/// Polymorphic JSON serialization for CARP, built on `json_serializable`.
///
/// [Serializable] adds a `__type` property to the JSON of each object, and
/// [FromJsonFactory] uses it to restore the right subclass on deserialization.
/// All CARP domain objects in `carp_core` and `carp_mobile_sensing` (protocols,
/// devices, tasks, triggers, measures, data) build on this, which lets the same
/// JSON be exchanged with the Kotlin CARP Core and the CARP web services.
///
/// Also re-exports [Uuid] from the `uuid` package for generating IDs.
library carp_serializable;

import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:json_annotation/json_annotation.dart';

export 'package:uuid/uuid.dart' show Uuid;

/*
 * Copyright 2022 Copenhagen Center for Health Technology (CACHET) at the
 * Technical University of Denmark (DTU).
 * Use of this source code is governed by a MIT-style license that can be
 * found in the LICENSE file.
 */

/// Base class for objects that serialize to and from polymorphic JSON.
///
/// Extend [Serializable] when a class hierarchy must round-trip through JSON
/// and the concrete subclass has to be restored on deserialization. Every
/// CARP domain object that is sent to or from a server (protocols, devices,
/// tasks, triggers, measures, data) builds on this class.
///
/// Key points:
///  * The concrete type is written to the `__type` property
///    ([CLASS_IDENTIFIER]); its value is [jsonType], which defaults to the
///    Dart [runtimeType].
///  * The actual (de)serialization code is generated by
///    [json_serializable](https://pub.dev/packages/json_serializable).
///  * A subclass must be registered in [FromJsonFactory] before JSON of that
///    type can be deserialized; otherwise a [SerializationException] is thrown.
///
/// To support polymorphic serialization, each subclass should:
///
///  * annotate the class with `@JsonSerializable`
///  * add the three JSON methods
///      * `Function get fromJsonFunction => ...`
///      * `factory ...fromJson(...)`
///      * `Map<String, dynamic> toJson() => ...`
///  * register the class in the [FromJsonFactory] registry
///  * generate the JSON functions with
///    `dart run build_runner build --delete-conflicting-outputs`
///
/// Below is an example of two classes `A` and `B` where `B` extends `A`.
///
/// ```dart
/// @JsonSerializable()
/// class A extends Serializable {
///   int? index;
///
///   A() : super();
///
///   @override
///   Function get fromJsonFunction => _$AFromJson;
///   factory A.fromJson(Map<String, dynamic> json) =>
///       FromJsonFactory().fromJson<A>(json);
///   @override
///   Map<String, dynamic> toJson() => _$AToJson(this);
/// }
///
/// @JsonSerializable()
/// class B extends A {
///   String? str;
///
///   B() : super();
///
///   @override
///   Function get fromJsonFunction => _$BFromJson;
///   factory B.fromJson(Map<String, dynamic> json) =>
///       FromJsonFactory().fromJson<B>(json);
///   @override
///   Map<String, dynamic> toJson() => _$BToJson(this);
/// }
/// ```
///
/// The names of the generated functions follow the
/// [json_serializable](https://pub.dev/packages/json_serializable) convention.
/// For example, the `fromJson` function for class `A` is called `_$AFromJson`.
///
/// The [fromJsonFunction] must be registered in the [FromJsonFactory]
/// singleton at app startup, before any deserialization:
///
/// ```dart
/// FromJsonFactory().register(A());
/// ```
///
/// An empty constructor is handy for this, but any constructor works, since
/// only [fromJsonFunction] is used.
///
/// By default, an object's [runtimeType] is used as the `__type`.
/// Hence, the JSON of objects of type `A` and `B` looks like this:
///
/// ```json
///  {
///   "__type": "A",
///   "index": 1
///  }
///  {
///   "__type": "B",
///   "index": 2,
///   "str": "abc"
///  }
/// ```
///
/// To use another type name (e.g., to match JSON produced by Kotlin, Java or
/// C#, which use package-qualified names), override [jsonType]:
///
/// ```dart
/// @JsonSerializable()
/// class B extends A {
///
///   <<as above>>
///
///   @override
///   String get jsonType => 'dk.cachet.$runtimeType';
/// }
/// ```
///
/// In which case the JSON looks like this:
///
/// ```json
///  {
///   "__type": "dk.cachet.B",
///   "index": 2,
///   "str": "abc"
///  }
/// ```
///
/// See also [toJsonString] for pretty-printing a serializable object.
abstract class Serializable {
  /// The identifier of the class type in JSON serialization.
  static const String CLASS_IDENTIFIER = '__type';

  /// The type name written to `__type` in JSON; set to [jsonType] on creation.
  ///
  /// Used by [FromJsonFactory] to pick the `fromJson` function when
  /// deserializing.
  @JsonKey(name: CLASS_IDENTIFIER)
  String? $type;

  /// Create an object that can be serialized to JSON.
  Serializable() {
    $type = jsonType;
  }

  /// The generated function that converts a JSON map to an object of this type.
  ///
  /// This is what [FromJsonFactory.register] stores.
  Function get fromJsonFunction;

  /// Returns a JSON map of this object, including the `__type` property.
  Map<String, dynamic> toJson();

  /// The `__type` used for JSON serialization of this class.
  ///
  /// Defaults to [runtimeType]. Override only if you need another name, e.g.,
  /// a fully qualified CARP Core name like
  /// `dk.cachet.carp.common.application.tasks.Measure.DataStream`.
  String get jsonType => runtimeType.toString();
}

/// Registry of `fromJson` functions used to deserialize [Serializable] objects.
///
/// This is a singleton: `FromJsonFactory()` always returns the same instance.
/// Each [Serializable] subclass registers its [Serializable.fromJsonFunction]
/// under its [Serializable.jsonType]. [fromJson] then reads the `__type` of a
/// JSON map and calls the matching function.
///
/// Key points:
///  * Register types at app startup, before deserializing. CARP packages do
///    this for you (e.g., `CarpMobileSensing.ensureInitialized()`).
///  * Registering the same type twice replaces the earlier function.
///  * Unknown types throw a [SerializationException], unless a fallback is
///    given with `notAvailable`.
class FromJsonFactory {
  static final FromJsonFactory _instance = FromJsonFactory._();
  factory FromJsonFactory() => _instance;

  final Map<String, Function> _registry = {};

  FromJsonFactory._();

  /// Registers [serializable] as a class which can be deserialized from JSON.
  ///
  /// If [type] is specified, it is used as the `__type` value
  /// ([Serializable.CLASS_IDENTIFIER]) to match.
  /// Otherwise [Serializable.jsonType] of [serializable] is used.
  /// Use [type] to map several JSON type names to the same class.
  ///
  /// A type needs to be registered **before** a class can be deserialized from
  /// JSON to a Dart class.
  void register(Serializable serializable, {String? type}) =>
      _registry[type ?? serializable.jsonType] = serializable.fromJsonFunction;

  /// Registers all [serializables].
  ///
  /// A convenient way to call [register] for multiple types.
  void registerAll(List<Serializable> serializables) {
    for (var serializable in serializables) {
      register(serializable);
    }
  }

  /// Deserializes [json] to an object of type [T], using its `__type` property.
  ///
  /// Returns the deserialized object if the `__type` of [json] has been
  /// registered and the registered function returns a [T].
  /// If the type is not registered, or the result is not a [T],
  /// [notAvailable] is returned (and a debug message printed) if specified.
  /// Otherwise, a [SerializationException] is thrown.
  T fromJson<T extends Serializable>(
    Map<String, dynamic> json, {
    T? notAvailable,
  }) {
    var message = '';
    final type = json[Serializable.CLASS_IDENTIFIER];
    if (!_registry.containsKey(type)) {
      message =
          "A 'fromJson' function was not found in the FromJsonFactory for the type '$type'. "
          "Register a Serializable class using the 'FromJsonFactory().register()' method."
          "\nIf you are using CARP Mobile Sensing, you can ensure json initialization by calling"
          "'CarpMobileSensing.ensureInitialized()' as part of your main method.";

      if (notAvailable != null) {
        debugPrint('$runtimeType - $message');
        return notAvailable;
      } else {
        throw SerializationException(message);
      }
    }

    var fromJson = Function.apply(_registry[type!]!, [json]);
    if (fromJson is T) return fromJson;

    message =
        "The 'fromJson' function registered for the type '$type' does not return an object of the correct type ('$T'). "
        "Make sure that the fromJson function returns a class of type '$T'.";

    if (notAvailable != null) {
      debugPrint('$runtimeType - $message');
      return notAvailable;
    } else {
      throw SerializationException(message);
    }
  }
}

/// Thrown when serialization to or from JSON fails.
///
/// [FromJsonFactory.fromJson] throws this when a `__type` is not registered
/// or maps to the wrong type.
class SerializationException implements Exception {
  final String _message;
  String get message => _message;
  SerializationException([this._message = '']);
  @override
  String toString() => '$runtimeType - $message';
}

/// Converts [object] to an indented JSON [String].
///
/// Useful for logging and debugging [Serializable] objects.
String toJsonString(Object? object) =>
    const JsonEncoder.withIndent(' ').convert(object);


