name: carp_movesense_package_example
description: Example project for the CAMS Movesense Sampling Package.
publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  carp_movesense_package:
    path: ../

dev_dependencies:
