name: carp_connectivity_package
description: CARP connectivity sampling package. Samples connectivity status, bluetooth devices, and wifi access points.
version: 1.8.1+1
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_connectivity_package

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"


dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^2.0.0
  carp_core: ^1.8.0
  carp_mobile_sensing: ^1.10.0
 
  json_annotation: ^4.8.0
  connectivity_plus: ^6.0.0    # connectivity events
  network_info_plus: ^6.0.0    # wifi ssid name
  flutter_blue_plus: ^1.35.0   # bluetooth scan
  crypto: ^3.0.0               # hashing sensitive data
  permission_handler: '>=11.0.0 <13.0.0'
  dchs_flutter_beacon: ^0.6.4


# Overriding carp libraries to use the local copy
# Remove this before release of package
# dependency_overrides:
#   carp_serializable:
#     path: ../../carp_serializable/
#   carp_core:
#     path: ../../carp_core/
  # carp_mobile_sensing:
  #   path: ../../carp_mobile_sensing/

dev_dependencies:
  flutter_lints: any
  build_runner: any
  json_serializable: any
  test: any

# This package only supports iOS and Android
platforms:
  android:
  ios:
