name: carp_movisens_package_example
description: Examples of how to use the CANS Movisens Package.
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  carp_movisens_package:
    path: ../

dev_dependencies:
#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true
 