name: carp_polar_package
description: The CARP Polar sampling package. Samples sensor data from the Polar H9, H10, and Verity Sense devices.
version: 0.40.1
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/packages/carp_polar_package

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.0.0
  carp_core: ^0.40.0
  carp_mobile_sensing: ^0.40.0
 
  json_annotation: ^4.7.0
  permission_handler: ^10.0.0  
  polar: ^3.4.0

# Overriding carp libraries to use the local copy
# Remove this before release of package
# dependency_overrides:
#   carp_core:
#     path: ../../carp_core/
#   carp_mobile_sensing:
#     path: ../../carp_mobile_sensing/

dev_dependencies:
  build_runner: any
  json_serializable: any
  test: any
  flutter_lints: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
