/*
 * Copyright 2026 the Technical University of Denmark (DTU).
 * Use of this source code is governed by a MIT-style license that can be
 * found in the LICENSE file.
 */

part of 'transportation.dart';

/// A no-op probe for the transportation package.
///
/// None of this package's data types ([Route], [Mode], [UserFeedback]) are
/// collected from a continuous phone sensor. Instead:
///
///  * a [Route] is built up by the app from location data (e.g. collected via
///    the `carp_context_package`'s location probe) and sent to a
///    classification server,
///  * a [Mode] is received back from that server,
///  * [UserFeedback] is generated by the app when the user interacts with
///    the classified route in the UI.
///
/// In all three cases, app-level code adds the resulting [Data] to this
/// probe once it is running, e.g.:
///
/// ```dart
/// transportationProbe.addMeasurement(Measurement.fromData(route));
/// transportationProbe.addMeasurement(Measurement.fromData(mode));
/// transportationProbe.addMeasurement(Measurement.fromData(userFeedback));
/// ```
///
/// This mirrors how the `carp_survey_package`'s `SurveyProbe` works.
class TransportationProbe extends Probe {}
